"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: b9d38665b0c9

from __future__ import annotations
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class AzureSourceConnectorConfigTypedDict(TypedDict):
    recursive: bool
    remote_url: str
    account_key: NotRequired[Nullable[str]]
    account_name: NotRequired[Nullable[str]]
    connection_string: NotRequired[Nullable[str]]
    sas_token: NotRequired[Nullable[str]]


class AzureSourceConnectorConfig(BaseModel):
    recursive: bool

    remote_url: str

    account_key: OptionalNullable[str] = UNSET

    account_name: OptionalNullable[str] = UNSET

    connection_string: OptionalNullable[str] = UNSET

    sas_token: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["account_key", "account_name", "connection_string", "sas_token"]
        )
        nullable_fields = set(
            ["account_key", "account_name", "connection_string", "sas_token"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
