"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import io
import json
import pydantic
from pydantic import ConfigDict, model_serializer, model_validator
from typing import IO, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    Unset,
)
from unstructured_client.utils import FieldMetadata, MultipartFormMetadata


def _drop_skip_preflight(raw: str, payload: dict) -> str:
    """Remove `skip_preflight` from `raw`, keeping every other byte where possible.

    The fold writes a known, fixed fragment, so clearing it can be its exact inverse rather
    than a re-encode. That matters: a re-encode preserves values but not their representation
    (``1e5`` becomes ``100000.0``), and it would be inconsistent to protect the caller's bytes
    when adding the flag and discard them when removing it.

    The candidate is parsed and compared before being accepted, so a fragment that happens to
    match a *nested* `skip_preflight` is rejected rather than silently corrupting the payload.
    A caller who wrote the key with their own spacing will not match the fragment at all; that
    falls back to a re-encode, which is correct but not byte-preserving.
    """
    expected = {k: v for k, v in payload.items() if k != "skip_preflight"}

    current = payload["skip_preflight"]
    if current is True or current is False:
        literal = "true" if current else "false"
        # Longest first: the comma form is what a non-empty object gets.
        for fragment in (
            f',"skip_preflight": {literal}',
            f'"skip_preflight": {literal}',
        ):
            # From the right: the fold always appends after existing content, so when the
            # payload also carries a nested `skip_preflight`, ours is the later one.
            index = raw.rfind(fragment)
            if index == -1:
                continue
            candidate = raw[:index] + raw[index + len(fragment) :]
            try:
                if json.loads(candidate) == expected:
                    return candidate
            except json.JSONDecodeError:
                continue

    return json.dumps(expected, ensure_ascii=False)


class InputFilesTypedDict(TypedDict):
    content: Union[bytes, IO[bytes], io.BufferedReader]
    file_name: str
    content_type: NotRequired[str]


class InputFiles(BaseModel):
    content: Annotated[
        Union[bytes, IO[bytes], io.BufferedReader],
        pydantic.Field(alias=""),
        FieldMetadata(multipart=MultipartFormMetadata(content=True)),
    ]

    file_name: Annotated[
        str, pydantic.Field(alias="fileName"), FieldMetadata(multipart=True)
    ]

    content_type: Annotated[
        Optional[str],
        pydantic.Field(alias="Content-Type"),
        FieldMetadata(multipart=True),
    ] = None


class BodyCreateJobTypedDict(TypedDict):
    request_data: str
    input_files: NotRequired[Nullable[List[InputFilesTypedDict]]]
    skip_preflight: NotRequired[Nullable[bool]]


class BodyCreateJob(BaseModel):
    # The only model here with a derived invariant across two fields: `skip_preflight` has to
    # end up inside `request_data`. Without this, `body.skip_preflight = True` after
    # construction would be silently dropped - the field carries no multipart metadata, so
    # nothing reaches the wire and nothing raises. Merged with the base config, not replacing it.
    model_config = ConfigDict(validate_assignment=True)

    request_data: Annotated[str, FieldMetadata(multipart=True)]

    input_files: Annotated[
        OptionalNullable[List[InputFiles]],
        FieldMetadata(multipart=MultipartFormMetadata(file=True)),
    ] = UNSET

    skip_preflight: OptionalNullable[bool] = UNSET
    r"""Skip the job preflight check for this job. Preflight runs by default.

    A convenience parameter, not a wire field: multipart has no ``skip_preflight`` part, so the
    server reads it out of the ``request_data`` JSON. The validator below writes it there, which
    is why this field deliberately carries no ``MultipartFormMetadata`` -- ``serialize_multipart_form``
    skips any field without it, so it never becomes a form field of its own.
    """

    @model_validator(mode="after")
    def fold_skip_preflight_into_request_data(self) -> "BodyCreateJob":
        """Validator entry point. The work is in ``_fold_skip_preflight`` so that
        ``model_copy`` can reuse it - a decorated validator is a descriptor, not a callable."""
        return self._fold_skip_preflight()

    def _fold_skip_preflight(self) -> "BodyCreateJob":
        """Write ``skip_preflight`` into ``request_data``, where the server reads it.

        Set explicitly, it wins over any value already in the JSON string: the parameter is the
        more specific expression of intent, and that includes ``None`` - "no preference" clears
        a value an earlier fold left behind. Left *unset*, ``request_data`` is passed through
        byte for byte, including a ``skip_preflight`` the caller wrote themselves.
        """
        # Tested with `isinstance`, not `is UNSET`: pydantic deep-copies the default per
        # instance, so an identity check against the UNSET singleton always fails and the
        # fold would run on every call.
        if isinstance(self.skip_preflight, Unset):
            # Never mentioned. `request_data` is the caller's bytes, including a
            # `skip_preflight` they wrote themselves; pass it through untouched.
            return self

        if self.skip_preflight is None:
            # Explicitly "no preference", which the server reads as "not set". If an earlier
            # fold left a value behind, drop it: the explicit argument wins over whatever is
            # in the string, and a stale `true` here would run the job with preflight off
            # after the caller cleared the flag.
            try:
                payload = json.loads(self.request_data)
            except json.JSONDecodeError:
                # Nothing was ever folded into a non-JSON payload, so there is nothing to
                # undo. Unlike the True/False paths, "no preference" has no reason to reject.
                return self
            if isinstance(payload, dict) and "skip_preflight" in payload:
                self.__dict__["request_data"] = _drop_skip_preflight(
                    self.request_data, payload
                )
            return self

        raw = self.request_data
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise ValueError(
                "request_data must be a JSON object to use skip_preflight; "
                f"could not parse it: {exc}"
            ) from exc
        if not isinstance(payload, dict):
            raise ValueError(
                "request_data must be a JSON object to use skip_preflight, "
                f"got {type(payload).__name__}"
            )

        literal = "true" if self.skip_preflight else "false"
        if payload.get("skip_preflight") is bool(self.skip_preflight):
            # Already folded and already correct. Returning early keeps this a genuine no-op:
            # `validate_assignment=True` re-runs the whole validator on *any* field assignment,
            # so without this, touching an unrelated field would push the payload down the
            # re-encode branch below and silently reformat it (1e5 -> 100000.0).
            return self

        if "skip_preflight" in payload:
            # The caller already put the key in the string. Replacing it in place would mean
            # locating its span in the raw text, so rewrite the document instead - and accept
            # that a re-encode is not lexically identical (0.1000 -> 0.1, 1e5 -> 100000.0).
            payload["skip_preflight"] = bool(self.skip_preflight)
            folded = json.dumps(payload, ensure_ascii=False)
        else:
            # The common case, and deliberately a text splice rather than a re-encode: a
            # json.loads/json.dumps round trip is lossy for number *representation* even
            # though it preserves value, and request_data carries caller configuration that
            # may be read by precision-sensitive consumers. Splicing leaves every other byte
            # exactly as handed to us.
            #
            # json.loads succeeded and produced a dict, so the last non-space character is
            # guaranteed to be the closing brace. Split the text around it and put every piece
            # back, so indentation and trailing newlines survive too - insignificant to a JSON
            # parser, but "every other byte" has to mean every other byte.
            stripped = raw.rstrip()
            trailing = raw[len(stripped) :]  # whitespace after the closing brace
            head = stripped[:-1]  # everything before the closing brace
            inner = head.rstrip()  # ...without the whitespace that preceded it
            gap = head[len(inner) :]  # ...and that whitespace, kept aside
            separator = "" if inner.endswith("{") else ","
            folded = (
                f'{inner}{separator}"skip_preflight": {literal}{gap}}}{trailing}'
            )

        # Written through __dict__ on purpose: a normal assignment would re-enter this
        # validator under validate_assignment=True and recurse until the stack blows.
        self.__dict__["request_data"] = folded
        return self

    def model_copy(self, *, update=None, deep=False) -> "BodyCreateJob":
        """Re-apply the fold after a copy.

        `model_copy` bypasses validation by design, so without this an updated
        `skip_preflight` never reaches `request_data`. The dangerous direction is
        `update={"skip_preflight": False}` on a body that already had it folded as `true`:
        the copy would keep sending `true` and run the job with preflight disabled while the
        caller believes they just re-enabled it.
        """
        copied = super().model_copy(update=update, deep=deep)
        if update and not {"skip_preflight", "request_data"}.isdisjoint(update):
            return copied._fold_skip_preflight()  # pylint: disable=protected-access
        # A copy that touches neither field is left strictly alone. Re-folding here would push
        # an already-folded payload down the re-encode branch and reformat it for no reason.
        return copied

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["input_files", "skip_preflight"]
        nullable_fields = ["input_files", "skip_preflight"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
