"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 0a63cb9d3b74

from __future__ import annotations
from .emailchannelresponse import EmailChannelResponse, EmailChannelResponseTypedDict
from .webhookchannelresponse import (
    WebhookChannelResponse,
    WebhookChannelResponseTypedDict,
)
from pydantic import Discriminator, Tag
from typing import List, Union
from typing_extensions import Annotated, TypeAliasType, TypedDict
from unstructured_client.types import BaseModel
from unstructured_client.utils import get_discriminator


ItemsTypedDict = TypeAliasType(
    "ItemsTypedDict",
    Union[WebhookChannelResponseTypedDict, EmailChannelResponseTypedDict],
)


Items = Annotated[
    Union[
        Annotated[EmailChannelResponse, Tag("email")],
        Annotated[WebhookChannelResponse, Tag("webhook")],
    ],
    Discriminator(lambda m: get_discriminator(m, "channel_type", "channel_type")),
]


class ChannelListResponseTypedDict(TypedDict):
    r"""List response for notification channels (no pagination, max 50 per scope)."""

    items: List[ItemsTypedDict]
    r"""List of channels"""


class ChannelListResponse(BaseModel):
    r"""List response for notification channels (no pagination, max 50 per scope)."""

    items: List[Items]
    r"""List of channels"""
