"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ConnectionCheckStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
