"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 8a9c5c5087f1

from __future__ import annotations
from enum import Enum


class ConnectionCheckStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
