"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sourceconnectortype import SourceConnectorType
from pydantic.functional_validators import PlainValidator
from typing import Any, Dict
from typing_extensions import Annotated, TypeAliasType, TypedDict
from unstructured_client.types import BaseModel
from unstructured_client.utils import validate_open_enum


CreateSourceConnectorConfigTypedDict = TypeAliasType(
    "CreateSourceConnectorConfigTypedDict",
    Dict[str, Any],
)


CreateSourceConnectorConfig = TypeAliasType(
    "CreateSourceConnectorConfig",
    Dict[str, Any],
)


class CreateSourceConnectorTypedDict(TypedDict):
    config: CreateSourceConnectorConfigTypedDict
    name: str
    type: SourceConnectorType


class CreateSourceConnector(BaseModel):
    config: CreateSourceConnectorConfig

    name: str

    type: Annotated[SourceConnectorType, PlainValidator(validate_open_enum(False))]
