"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4577e2aecc77

from __future__ import annotations
from .emailchannelconfig import EmailChannelConfig, EmailChannelConfigTypedDict
from .notificationeventtype import NotificationEventType
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from unstructured_client.utils import validate_const


class CreateEmailChannelRequestTypedDict(TypedDict):
    r"""Request to create an email notification channel."""

    email_config: EmailChannelConfigTypedDict
    r"""User-configurable email settings."""
    event_types: List[NotificationEventType]
    r"""Event types to subscribe to"""
    channel_type: Literal["email"]
    description: NotRequired[Nullable[str]]
    r"""Channel description"""
    enabled: NotRequired[bool]
    r"""Enable/disable channel"""


class CreateEmailChannelRequest(BaseModel):
    r"""Request to create an email notification channel."""

    email_config: EmailChannelConfig
    r"""User-configurable email settings."""

    event_types: List[NotificationEventType]
    r"""Event types to subscribe to"""

    CHANNEL_TYPE: Annotated[
        Annotated[Optional[Literal["email"]], AfterValidator(validate_const("email"))],
        pydantic.Field(alias="channel_type"),
    ] = "email"

    description: OptionalNullable[str] = UNSET
    r"""Channel description"""

    enabled: Optional[bool] = True
    r"""Enable/disable channel"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channel_type", "description", "enabled"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CreateEmailChannelRequest.model_rebuild()
except NameError:
    pass
