"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 081cd5c7dfd6

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from unstructured_client.types import BaseModel, UNSET_SENTINEL


class DatabricksVolumesConnectorConfigInputTypedDict(TypedDict):
    catalog: str
    client_id: str
    client_secret: str
    host: str
    volume: str
    volume_path: str
    schema_: NotRequired[str]


class DatabricksVolumesConnectorConfigInput(BaseModel):
    catalog: str

    client_id: str

    client_secret: str

    host: str

    volume: str

    volume_path: str

    schema_: Annotated[Optional[str], pydantic.Field(alias="schema")] = "default"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["schema"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DatabricksVolumesConnectorConfigInput.model_rebuild()
except NameError:
    pass
