"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4e2cecb36d1c

from __future__ import annotations
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class EmailChannelConfigUpdateTypedDict(TypedDict):
    r"""User-configurable email settings."""

    cc: NotRequired[Nullable[List[str]]]
    r"""CC email addresses (if provider supports)"""
    recipient_email: NotRequired[Nullable[str]]
    r"""Primary recipient email address"""
    reply_to: NotRequired[Nullable[str]]
    r"""Reply-to email address"""


class EmailChannelConfigUpdate(BaseModel):
    r"""User-configurable email settings."""

    cc: OptionalNullable[List[str]] = UNSET
    r"""CC email addresses (if provider supports)"""

    recipient_email: OptionalNullable[str] = UNSET
    r"""Primary recipient email address"""

    reply_to: OptionalNullable[str] = UNSET
    r"""Reply-to email address"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["cc", "recipient_email", "reply_to"]
        nullable_fields = ["cc", "recipient_email", "reply_to"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
