"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4e2cecb36d1c

from __future__ import annotations
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class EmailChannelConfigUpdateTypedDict(TypedDict):
    r"""User-configurable email settings."""

    cc: NotRequired[Nullable[List[str]]]
    r"""CC email addresses (if provider supports)"""
    recipient_email: NotRequired[Nullable[str]]
    r"""Primary recipient email address"""
    reply_to: NotRequired[Nullable[str]]
    r"""Reply-to email address"""


class EmailChannelConfigUpdate(BaseModel):
    r"""User-configurable email settings."""

    cc: OptionalNullable[List[str]] = UNSET
    r"""CC email addresses (if provider supports)"""

    recipient_email: OptionalNullable[str] = UNSET
    r"""Primary recipient email address"""

    reply_to: OptionalNullable[str] = UNSET
    r"""Reply-to email address"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cc", "recipient_email", "reply_to"])
        nullable_fields = set(["cc", "recipient_email", "reply_to"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
