"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class EncryptionType(str, Enum):
    RSA = "rsa"
    RSA_AES = "rsa_aes"
