"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from unstructured_client.types import BaseModel


class EncryptionCertificateResponseTypedDict(TypedDict):
    r"""Response model for the encryption certificate.
    Contains the siged user certificate and the root CA certificate
    for verification.
    """

    ca_chain: str
    encryption_certificate: str


class EncryptionCertificateResponse(BaseModel):
    r"""Response model for the encryption certificate.
    Contains the siged user certificate and the root CA certificate
    for verification.
    """

    ca_chain: str

    encryption_certificate: str
