"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 69897cb39f5b

from __future__ import annotations
from typing_extensions import TypedDict
from unstructured_client.types import BaseModel


class GCSDestinationConnectorConfigTypedDict(TypedDict):
    remote_url: str
    service_account_key: str


class GCSDestinationConnectorConfig(BaseModel):
    remote_url: str

    service_account_key: str
