"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 91b43895c7a9

from __future__ import annotations
from .secretreference import SecretReference, SecretReferenceTypedDict
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


GoogleDriveSourceConnectorConfigInputOauthTokenTypedDict = TypeAliasType(
    "GoogleDriveSourceConnectorConfigInputOauthTokenTypedDict",
    Union[SecretReferenceTypedDict, str],
)


GoogleDriveSourceConnectorConfigInputOauthToken = TypeAliasType(
    "GoogleDriveSourceConnectorConfigInputOauthToken", Union[SecretReference, str]
)


GoogleDriveSourceConnectorConfigInputServiceAccountKeyTypedDict = TypeAliasType(
    "GoogleDriveSourceConnectorConfigInputServiceAccountKeyTypedDict",
    Union[SecretReferenceTypedDict, str],
)


GoogleDriveSourceConnectorConfigInputServiceAccountKey = TypeAliasType(
    "GoogleDriveSourceConnectorConfigInputServiceAccountKey",
    Union[SecretReference, str],
)


class GoogleDriveSourceConnectorConfigInputTypedDict(TypedDict):
    drive_id: str
    extensions: NotRequired[Nullable[List[str]]]
    oauth_token: NotRequired[
        Nullable[GoogleDriveSourceConnectorConfigInputOauthTokenTypedDict]
    ]
    recursive: NotRequired[bool]
    service_account_key: NotRequired[
        Nullable[GoogleDriveSourceConnectorConfigInputServiceAccountKeyTypedDict]
    ]


class GoogleDriveSourceConnectorConfigInput(BaseModel):
    drive_id: str

    extensions: OptionalNullable[List[str]] = UNSET

    oauth_token: OptionalNullable[GoogleDriveSourceConnectorConfigInputOauthToken] = (
        UNSET
    )

    recursive: Optional[bool] = True

    service_account_key: OptionalNullable[
        GoogleDriveSourceConnectorConfigInputServiceAccountKey
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["extensions", "oauth_token", "recursive", "service_account_key"]
        )
        nullable_fields = set(["extensions", "oauth_token", "service_account_key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
