"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 143fbb60a474

from __future__ import annotations
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class JiraSourceConnectorConfigInputTypedDict(TypedDict):
    url: str
    username: str
    boards: NotRequired[Nullable[List[str]]]
    cloud: NotRequired[Nullable[bool]]
    download_attachments: NotRequired[Nullable[bool]]
    issues: NotRequired[Nullable[List[str]]]
    password: NotRequired[Nullable[str]]
    projects: NotRequired[Nullable[List[str]]]
    status_filters: NotRequired[Nullable[List[str]]]
    token: NotRequired[Nullable[str]]


class JiraSourceConnectorConfigInput(BaseModel):
    url: str

    username: str

    boards: OptionalNullable[List[str]] = UNSET

    cloud: OptionalNullable[bool] = UNSET

    download_attachments: OptionalNullable[bool] = UNSET

    issues: OptionalNullable[List[str]] = UNSET

    password: OptionalNullable[str] = UNSET

    projects: OptionalNullable[List[str]] = UNSET

    status_filters: OptionalNullable[List[str]] = UNSET

    token: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "boards",
                "cloud",
                "download_attachments",
                "issues",
                "password",
                "projects",
                "status_filters",
                "token",
            ]
        )
        nullable_fields = set(
            [
                "boards",
                "cloud",
                "download_attachments",
                "issues",
                "password",
                "projects",
                "status_filters",
                "token",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
