"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 42b015a934ba

from __future__ import annotations
from .jobstatus import JobStatus
from .nodefilemetadata import NodeFileMetadata, NodeFileMetadataTypedDict
from .workflowjobtype import WorkflowJobType
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class JobInformationTypedDict(TypedDict):
    created_at: datetime
    id: str
    status: JobStatus
    workflow_id: str
    workflow_name: str
    input_file_ids: NotRequired[Nullable[List[str]]]
    job_type: NotRequired[WorkflowJobType]
    output_node_files: NotRequired[Nullable[List[NodeFileMetadataTypedDict]]]
    runtime: NotRequired[Nullable[str]]


class JobInformation(BaseModel):
    created_at: datetime

    id: str

    status: JobStatus

    workflow_id: str

    workflow_name: str

    input_file_ids: OptionalNullable[List[str]] = UNSET

    job_type: Optional[WorkflowJobType] = None

    output_node_files: OptionalNullable[List[NodeFileMetadata]] = UNSET

    runtime: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["input_file_ids", "job_type", "output_node_files", "runtime"]
        )
        nullable_fields = set(["input_file_ids", "output_node_files", "runtime"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
