"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class MarkReadRequestTypedDict(TypedDict):
    r"""Request to mark notifications as read.

    Provide ONE of: notification_ids, before, or mark_all (mutually exclusive).
    workflow_id is valid with 'before' or 'mark_all'.
    """

    before: NotRequired[Nullable[datetime]]
    r"""Mark all notifications created before this ISO 8601 timestamp as read"""
    mark_all: NotRequired[bool]
    r"""Mark all unread notifications as read (can combine with workflow_id)"""
    notification_ids: NotRequired[Nullable[List[str]]]
    r"""Specific notification IDs to mark as read (max 100)"""
    workflow_id: NotRequired[Nullable[str]]
    r"""Filter by workflow (only valid with 'before' or 'mark_all')"""


class MarkReadRequest(BaseModel):
    r"""Request to mark notifications as read.

    Provide ONE of: notification_ids, before, or mark_all (mutually exclusive).
    workflow_id is valid with 'before' or 'mark_all'.
    """

    before: OptionalNullable[datetime] = UNSET
    r"""Mark all notifications created before this ISO 8601 timestamp as read"""

    mark_all: Optional[bool] = False
    r"""Mark all unread notifications as read (can combine with workflow_id)"""

    notification_ids: OptionalNullable[List[str]] = UNSET
    r"""Specific notification IDs to mark as read (max 100)"""

    workflow_id: OptionalNullable[str] = UNSET
    r"""Filter by workflow (only valid with 'before' or 'mark_all')"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["before", "mark_all", "notification_ids", "workflow_id"]
        nullable_fields = ["before", "notification_ids", "workflow_id"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
