"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 3bb85779fd20

from __future__ import annotations
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class MilvusDestinationConnectorConfigTypedDict(TypedDict):
    collection_name: str
    record_id_key: str
    uri: str
    db_name: NotRequired[Nullable[str]]
    password: NotRequired[Nullable[str]]
    token: NotRequired[Nullable[str]]
    user: NotRequired[Nullable[str]]


class MilvusDestinationConnectorConfig(BaseModel):
    collection_name: str

    record_id_key: str

    uri: str

    db_name: OptionalNullable[str] = UNSET

    password: OptionalNullable[str] = UNSET

    token: OptionalNullable[str] = UNSET

    user: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["db_name", "password", "token", "user"])
        nullable_fields = set(["db_name", "password", "token", "user"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
