"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing_extensions import TypedDict
from unstructured_client.types import BaseModel


class NodeFileMetadataTypedDict(TypedDict):
    file_id: str
    node_id: str


class NodeFileMetadata(BaseModel):
    file_id: str

    node_id: str
