"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import BaseModel


class PostgresSourceConnectorConfigInputTypedDict(TypedDict):
    database: str
    host: str
    password: str
    table_name: str
    username: str
    batch_size: NotRequired[int]
    port: NotRequired[int]


class PostgresSourceConnectorConfigInput(BaseModel):
    database: str

    host: str

    password: str

    table_name: str

    username: str

    batch_size: Optional[int] = 100

    port: Optional[int] = 5432
