"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class RedisDestinationConnectorConfigInputTypedDict(TypedDict):
    host: str
    batch_size: NotRequired[int]
    database: NotRequired[int]
    password: NotRequired[Nullable[str]]
    port: NotRequired[int]
    ssl: NotRequired[bool]
    uri: NotRequired[Nullable[str]]
    username: NotRequired[Nullable[str]]


class RedisDestinationConnectorConfigInput(BaseModel):
    host: str

    batch_size: Optional[int] = 100

    database: Optional[int] = 0

    password: OptionalNullable[str] = UNSET

    port: Optional[int] = 6379

    ssl: Optional[bool] = True

    uri: OptionalNullable[str] = UNSET

    username: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "batch_size",
            "database",
            "password",
            "port",
            "ssl",
            "uri",
            "username",
        ]
        nullable_fields = ["password", "uri", "username"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
