"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d91631160e6b

from __future__ import annotations
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class S3DestinationConnectorConfigTypedDict(TypedDict):
    anonymous: bool
    remote_url: str
    ambient_credentials: NotRequired[Nullable[bool]]
    endpoint_url: NotRequired[Nullable[str]]
    key: NotRequired[Nullable[str]]
    secret: NotRequired[Nullable[str]]
    token: NotRequired[Nullable[str]]


class S3DestinationConnectorConfig(BaseModel):
    anonymous: bool

    remote_url: str

    ambient_credentials: OptionalNullable[bool] = UNSET

    endpoint_url: OptionalNullable[str] = UNSET

    key: OptionalNullable[str] = UNSET

    secret: OptionalNullable[str] = UNSET

    token: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["ambient_credentials", "endpoint_url", "key", "secret", "token"]
        )
        nullable_fields = set(
            ["ambient_credentials", "endpoint_url", "key", "secret", "token"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
