"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 973a768cccba

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class TeradataDestinationConnectorConfigInputTypedDict(TypedDict):
    host: str
    password: str
    user: str
    batch_size: NotRequired[int]
    database: NotRequired[Nullable[str]]
    dbs_port: NotRequired[int]
    record_id_key: NotRequired[Nullable[str]]
    table_name: NotRequired[str]


class TeradataDestinationConnectorConfigInput(BaseModel):
    host: str

    password: str

    user: str

    batch_size: Optional[int] = 50

    database: OptionalNullable[str] = UNSET

    dbs_port: Optional[int] = 1025

    record_id_key: OptionalNullable[str] = UNSET

    table_name: Optional[str] = "elements"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["batch_size", "database", "dbs_port", "record_id_key", "table_name"]
        )
        nullable_fields = set(["database", "record_id_key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
