"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: ac89acfb15c6

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)


class TeradataSourceConnectorConfigTypedDict(TypedDict):
    host: str
    password: str
    table_name: str
    user: str
    batch_size: NotRequired[int]
    database: NotRequired[Nullable[str]]
    dbs_port: NotRequired[int]
    fields: NotRequired[Nullable[List[str]]]
    id_column: NotRequired[str]


class TeradataSourceConnectorConfig(BaseModel):
    host: str

    password: str

    table_name: str

    user: str

    batch_size: Optional[int] = 100

    database: OptionalNullable[str] = UNSET

    dbs_port: Optional[int] = 1025

    fields: OptionalNullable[List[str]] = UNSET

    id_column: Optional[str] = "id"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["batch_size", "database", "dbs_port", "fields", "id_column"]
        )
        nullable_fields = set(["database", "fields"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
