"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Any, Dict
from typing_extensions import TypedDict
from unstructured_client.types import BaseModel


class UpdateSourceConnectorTypedDict(TypedDict):
    config: Dict[str, Any]


class UpdateSourceConnector(BaseModel):
    config: Dict[str, Any]
