"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .azuresourceconnectorconfiginput import (
    AzureSourceConnectorConfigInput,
    AzureSourceConnectorConfigInputTypedDict,
)
from .boxsourceconnectorconfiginput import (
    BoxSourceConnectorConfigInput,
    BoxSourceConnectorConfigInputTypedDict,
)
from .confluencesourceconnectorconfiginput import (
    ConfluenceSourceConnectorConfigInput,
    ConfluenceSourceConnectorConfigInputTypedDict,
)
from .couchbasesourceconnectorconfiginput import (
    CouchbaseSourceConnectorConfigInput,
    CouchbaseSourceConnectorConfigInputTypedDict,
)
from .databricksvolumesconnectorconfiginput import (
    DatabricksVolumesConnectorConfigInput,
    DatabricksVolumesConnectorConfigInputTypedDict,
)
from .dropboxsourceconnectorconfiginput import (
    DropboxSourceConnectorConfigInput,
    DropboxSourceConnectorConfigInputTypedDict,
)
from .elasticsearchconnectorconfiginput import (
    ElasticsearchConnectorConfigInput,
    ElasticsearchConnectorConfigInputTypedDict,
)
from .gcssourceconnectorconfiginput import (
    GCSSourceConnectorConfigInput,
    GCSSourceConnectorConfigInputTypedDict,
)
from .googledrivesourceconnectorconfiginput import (
    GoogleDriveSourceConnectorConfigInput,
    GoogleDriveSourceConnectorConfigInputTypedDict,
)
from .jirasourceconnectorconfiginput import (
    JiraSourceConnectorConfigInput,
    JiraSourceConnectorConfigInputTypedDict,
)
from .kafkacloudsourceconnectorconfiginput import (
    KafkaCloudSourceConnectorConfigInput,
    KafkaCloudSourceConnectorConfigInputTypedDict,
)
from .mongodbconnectorconfiginput import (
    MongoDBConnectorConfigInput,
    MongoDBConnectorConfigInputTypedDict,
)
from .onedrivesourceconnectorconfiginput import (
    OneDriveSourceConnectorConfigInput,
    OneDriveSourceConnectorConfigInputTypedDict,
)
from .outlooksourceconnectorconfiginput import (
    OutlookSourceConnectorConfigInput,
    OutlookSourceConnectorConfigInputTypedDict,
)
from .postgressourceconnectorconfiginput import (
    PostgresSourceConnectorConfigInput,
    PostgresSourceConnectorConfigInputTypedDict,
)
from .s3sourceconnectorconfiginput import (
    S3SourceConnectorConfigInput,
    S3SourceConnectorConfigInputTypedDict,
)
from .salesforcesourceconnectorconfiginput import (
    SalesforceSourceConnectorConfigInput,
    SalesforceSourceConnectorConfigInputTypedDict,
)
from .sharepointsourceconnectorconfiginput import (
    SharePointSourceConnectorConfigInput,
    SharePointSourceConnectorConfigInputTypedDict,
)
from .snowflakesourceconnectorconfiginput import (
    SnowflakeSourceConnectorConfigInput,
    SnowflakeSourceConnectorConfigInputTypedDict,
)
from .zendesksourceconnectorconfiginput import (
    ZendeskSourceConnectorConfigInput,
    ZendeskSourceConnectorConfigInputTypedDict,
)
from typing import Any, Dict, Union
from typing_extensions import TypeAliasType, TypedDict
from unstructured_client.types import BaseModel


UpdateSourceConnectorConfigTypedDict = TypeAliasType(
    "UpdateSourceConnectorConfigTypedDict",
    Union[
        MongoDBConnectorConfigInputTypedDict,
        BoxSourceConnectorConfigInputTypedDict,
        DropboxSourceConnectorConfigInputTypedDict,
        ElasticsearchConnectorConfigInputTypedDict,
        GCSSourceConnectorConfigInputTypedDict,
        SalesforceSourceConnectorConfigInputTypedDict,
        GoogleDriveSourceConnectorConfigInputTypedDict,
        ZendeskSourceConnectorConfigInputTypedDict,
        AzureSourceConnectorConfigInputTypedDict,
        OneDriveSourceConnectorConfigInputTypedDict,
        KafkaCloudSourceConnectorConfigInputTypedDict,
        OutlookSourceConnectorConfigInputTypedDict,
        DatabricksVolumesConnectorConfigInputTypedDict,
        S3SourceConnectorConfigInputTypedDict,
        CouchbaseSourceConnectorConfigInputTypedDict,
        SharePointSourceConnectorConfigInputTypedDict,
        PostgresSourceConnectorConfigInputTypedDict,
        JiraSourceConnectorConfigInputTypedDict,
        ConfluenceSourceConnectorConfigInputTypedDict,
        SnowflakeSourceConnectorConfigInputTypedDict,
        Dict[str, Any],
    ],
)


UpdateSourceConnectorConfig = TypeAliasType(
    "UpdateSourceConnectorConfig",
    Union[
        MongoDBConnectorConfigInput,
        BoxSourceConnectorConfigInput,
        DropboxSourceConnectorConfigInput,
        ElasticsearchConnectorConfigInput,
        GCSSourceConnectorConfigInput,
        SalesforceSourceConnectorConfigInput,
        GoogleDriveSourceConnectorConfigInput,
        ZendeskSourceConnectorConfigInput,
        AzureSourceConnectorConfigInput,
        OneDriveSourceConnectorConfigInput,
        KafkaCloudSourceConnectorConfigInput,
        OutlookSourceConnectorConfigInput,
        DatabricksVolumesConnectorConfigInput,
        S3SourceConnectorConfigInput,
        CouchbaseSourceConnectorConfigInput,
        SharePointSourceConnectorConfigInput,
        PostgresSourceConnectorConfigInput,
        JiraSourceConnectorConfigInput,
        ConfluenceSourceConnectorConfigInput,
        SnowflakeSourceConnectorConfigInput,
        Dict[str, Any],
    ],
)


class UpdateSourceConnectorTypedDict(TypedDict):
    config: UpdateSourceConnectorConfigTypedDict


class UpdateSourceConnector(BaseModel):
    config: UpdateSourceConnectorConfig
