"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Any, Dict
from typing_extensions import TypeAliasType, TypedDict
from unstructured_client.types import BaseModel


UpdateSourceConnectorConfigTypedDict = TypeAliasType(
    "UpdateSourceConnectorConfigTypedDict",
    Dict[str, Any],
)


UpdateSourceConnectorConfig = TypeAliasType(
    "UpdateSourceConnectorConfig",
    Dict[str, Any],
)


class UpdateSourceConnectorTypedDict(TypedDict):
    config: UpdateSourceConnectorConfigTypedDict


class UpdateSourceConnector(BaseModel):
    config: UpdateSourceConnectorConfig
