"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import List, Union
from typing_extensions import TypedDict
from unstructured_client.types import BaseModel


LocTypedDict = Union[str, int]


Loc = Union[str, int]


class ValidationErrorTypedDict(TypedDict):
    loc: List[LocTypedDict]
    msg: str
    type: str


class ValidationError(BaseModel):
    loc: List[Loc]

    msg: str

    type: str
