"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Any, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict
from unstructured_client.types import BaseModel


class ContextTypedDict(TypedDict):
    pass


class Context(BaseModel):
    pass


LocTypedDict = TypeAliasType("LocTypedDict", Union[str, int])


Loc = TypeAliasType("Loc", Union[str, int])


class ValidationErrorTypedDict(TypedDict):
    loc: List[LocTypedDict]
    msg: str
    type: str
    ctx: NotRequired[ContextTypedDict]
    input: NotRequired[Any]


class ValidationError(BaseModel):
    loc: List[Loc]

    msg: str

    type: str

    ctx: Optional[Context] = None

    input: Optional[Any] = None
