"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 619fd2422642

from __future__ import annotations
from pydantic import model_serializer
from typing import Any, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict
from unstructured_client.types import BaseModel, UNSET_SENTINEL


class ContextTypedDict(TypedDict):
    pass


class Context(BaseModel):
    pass


LocTypedDict = TypeAliasType("LocTypedDict", Union[str, int])


Loc = TypeAliasType("Loc", Union[str, int])


class ValidationErrorTypedDict(TypedDict):
    loc: List[LocTypedDict]
    msg: str
    type: str
    ctx: NotRequired[ContextTypedDict]
    input: NotRequired[Any]


class ValidationError(BaseModel):
    loc: List[Loc]

    msg: str

    type: str

    ctx: Optional[Context] = None

    input: Optional[Any] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ctx", "input"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
