"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 8d984e4e98c1

from __future__ import annotations
from datetime import datetime
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from unstructured_client.utils import validate_const


class WebhookChannelResponseTypedDict(TypedDict):
    r"""Response for webhook notification channel."""

    created_at: datetime
    r"""Creation timestamp"""
    enabled: bool
    r"""Channel enabled status"""
    event_types: List[str]
    r"""Subscribed event types"""
    id: str
    r"""Channel ID"""
    updated_at: datetime
    r"""Last update timestamp"""
    url: str
    r"""Webhook endpoint URL"""
    channel_type: Literal["webhook"]
    description: NotRequired[Nullable[str]]
    r"""Channel description"""


class WebhookChannelResponse(BaseModel):
    r"""Response for webhook notification channel."""

    created_at: datetime
    r"""Creation timestamp"""

    enabled: bool
    r"""Channel enabled status"""

    event_types: List[str]
    r"""Subscribed event types"""

    id: str
    r"""Channel ID"""

    updated_at: datetime
    r"""Last update timestamp"""

    url: str
    r"""Webhook endpoint URL"""

    CHANNEL_TYPE: Annotated[
        Annotated[
            Optional[Literal["webhook"]], AfterValidator(validate_const("webhook"))
        ],
        pydantic.Field(alias="channel_type"),
    ] = "webhook"

    description: OptionalNullable[str] = UNSET
    r"""Channel description"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["channel_type", "description"]
        nullable_fields = ["description"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
