"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 8d984e4e98c1

from __future__ import annotations
from datetime import datetime
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from unstructured_client.utils import validate_const


class WebhookChannelResponseTypedDict(TypedDict):
    r"""Response for webhook notification channel."""

    created_at: datetime
    r"""Creation timestamp"""
    enabled: bool
    r"""Channel enabled status"""
    event_types: List[str]
    r"""Subscribed event types"""
    id: str
    r"""Channel ID"""
    updated_at: datetime
    r"""Last update timestamp"""
    url: str
    r"""Webhook endpoint URL"""
    channel_type: Literal["webhook"]
    description: NotRequired[Nullable[str]]
    r"""Channel description"""


class WebhookChannelResponse(BaseModel):
    r"""Response for webhook notification channel."""

    created_at: datetime
    r"""Creation timestamp"""

    enabled: bool
    r"""Channel enabled status"""

    event_types: List[str]
    r"""Subscribed event types"""

    id: str
    r"""Channel ID"""

    updated_at: datetime
    r"""Last update timestamp"""

    url: str
    r"""Webhook endpoint URL"""

    CHANNEL_TYPE: Annotated[
        Annotated[
            Optional[Literal["webhook"]], AfterValidator(validate_const("webhook"))
        ],
        pydantic.Field(alias="channel_type"),
    ] = "webhook"

    description: OptionalNullable[str] = UNSET
    r"""Channel description"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channel_type", "description"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    WebhookChannelResponse.model_rebuild()
except NameError:
    pass
