"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 3ca964fbc8c2

from __future__ import annotations
from enum import Enum


class WorkflowJobType(str, Enum):
    EPHEMERAL = "ephemeral"
    PERSISTENT = "persistent"
    SCHEDULED = "scheduled"
    TEMPLATE = "template"
