"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import body_pipeline_1_general_v0_general_post as shared_body_pipeline_1_general_v0_general_post
from typing import Any, Optional



@dataclasses.dataclass
class Pipeline1GeneralV0GeneralPostRequest:
    body_pipeline_1_general_v0_general_post: Optional[shared_body_pipeline_1_general_v0_general_post.BodyPipeline1GeneralV0GeneralPost] = dataclasses.field(default=None, metadata={'request': { 'media_type': 'multipart/form-data' }})
    unstructured_api_key: Optional[str] = dataclasses.field(default=None, metadata={'header': { 'field_name': 'unstructured-api-key', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class Pipeline1GeneralV0GeneralPostResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    pipeline_1_general_v0_general_post_200_application_json_any: Optional[Any] = dataclasses.field(default=None)
    r"""Successful Response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

