"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 5849e129665f

import importlib.metadata

__title__: str = "unstructured-client"
__version__: str = "0.42.12"
__openapi_doc_version__: str = "1.5.19"
__gen_version__: str = "2.879.6"
__user_agent__: str = "speakeasy-sdk/python 0.42.12 2.879.6 1.5.19 unstructured-client"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
