"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "unstructured-client"
__version__: str = "0.30.1"
__openapi_doc_version__: str = "1.0.0"
__gen_version__: str = "2.512.4"
__user_agent__: str = "speakeasy-sdk/python 0.30.1 2.512.4 1.0.0 unstructured-client"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
