"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from typing import Optional



@dataclasses.dataclass
class BodyPipeline1GeneralV0042GeneralPost:
    coordinates: Optional[list[str]] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'coordinates' }})
    encoding: Optional[list[str]] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'encoding' }})
    files: Optional[list[bytes]] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'files', 'json': True }})
    gz_uncompressed_content_type: Optional[str] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'gz_uncompressed_content_type' }})
    hi_res_model_name: Optional[list[str]] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'hi_res_model_name' }})
    include_page_breaks: Optional[list[str]] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'include_page_breaks' }})
    ocr_languages: Optional[list[str]] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'ocr_languages' }})
    output_format: Optional[str] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'output_format' }})
    pdf_infer_table_structure: Optional[list[str]] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'pdf_infer_table_structure' }})
    skip_infer_table_types: Optional[list[str]] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'skip_infer_table_types' }})
    strategy: Optional[list[str]] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'strategy' }})
    xml_keep_tags: Optional[list[str]] = dataclasses.field(default=None, metadata={'multipart_form': { 'field_name': 'xml_keep_tags' }})
    

