workflowVersion: 1.0.0
sources:
    my-source:
        inputs:
            - location: https://api.unstructured.io/general/openapi.json
        overlays:
            - location: ./overlay_client.yaml
targets:
    unstructured-python:
        target: python
        source: my-source
        # publish:
        #     pypi:
        #         token: $PYPI_TOKEN
