"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 0b5101a05985

from __future__ import annotations
import httpx
import pydantic
from pydantic import model_serializer
from typing_extensions import Annotated, NotRequired, TypedDict
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from unstructured_client.utils import FieldMetadata, HeaderMetadata, PathParamMetadata


class DeleteWorkflowChannelAPIV1WorkflowsWorkflowIDNotificationsChannelsChannelIDDeleteRequestTypedDict(
    TypedDict
):
    channel_id: str
    workflow_id: str
    unstructured_api_key: NotRequired[Nullable[str]]


class DeleteWorkflowChannelAPIV1WorkflowsWorkflowIDNotificationsChannelsChannelIDDeleteRequest(
    BaseModel
):
    channel_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    workflow_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    unstructured_api_key: Annotated[
        OptionalNullable[str],
        pydantic.Field(alias="unstructured-api-key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["unstructured-api-key"])
        nullable_fields = set(["unstructured-api-key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class DeleteWorkflowChannelAPIV1WorkflowsWorkflowIDNotificationsChannelsChannelIDDeleteResponseTypedDict(
    TypedDict
):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""


class DeleteWorkflowChannelAPIV1WorkflowsWorkflowIDNotificationsChannelsChannelIDDeleteResponse(
    BaseModel
):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
