"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: b056361a65e9

from __future__ import annotations
import httpx
import pydantic
from pydantic import Discriminator, Tag, model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict
from unstructured_client.models.shared import (
    emailchannelresponse as shared_emailchannelresponse,
    updatechannelrequest as shared_updatechannelrequest,
    webhookchannelresponse as shared_webhookchannelresponse,
)
from unstructured_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from unstructured_client.utils import (
    FieldMetadata,
    HeaderMetadata,
    PathParamMetadata,
    RequestMetadata,
    get_discriminator,
)


class UpdateChannelAPIV1NotificationsChannelsChannelIDPatchRequestTypedDict(TypedDict):
    update_channel_request: shared_updatechannelrequest.UpdateChannelRequestTypedDict
    channel_id: str
    unstructured_api_key: NotRequired[Nullable[str]]


class UpdateChannelAPIV1NotificationsChannelsChannelIDPatchRequest(BaseModel):
    update_channel_request: Annotated[
        shared_updatechannelrequest.UpdateChannelRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    channel_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    unstructured_api_key: Annotated[
        OptionalNullable[str],
        pydantic.Field(alias="unstructured-api-key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["unstructured-api-key"])
        nullable_fields = set(["unstructured-api-key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


UpdateChannelAPIV1NotificationsChannelsChannelIDPatchResponseUpdateChannelAPIV1NotificationsChannelsChannelIDPatchTypedDict = TypeAliasType(
    "UpdateChannelAPIV1NotificationsChannelsChannelIDPatchResponseUpdateChannelAPIV1NotificationsChannelsChannelIDPatchTypedDict",
    Union[
        shared_webhookchannelresponse.WebhookChannelResponseTypedDict,
        shared_emailchannelresponse.EmailChannelResponseTypedDict,
    ],
)
r"""Successful Response"""


UpdateChannelAPIV1NotificationsChannelsChannelIDPatchResponseUpdateChannelAPIV1NotificationsChannelsChannelIDPatch = Annotated[
    Union[
        Annotated[shared_emailchannelresponse.EmailChannelResponse, Tag("email")],
        Annotated[shared_webhookchannelresponse.WebhookChannelResponse, Tag("webhook")],
    ],
    Discriminator(lambda m: get_discriminator(m, "channel_type", "channel_type")),
]
r"""Successful Response"""


class UpdateChannelAPIV1NotificationsChannelsChannelIDPatchResponseTypedDict(TypedDict):
    content_type: str
    r"""HTTP response content type for this operation"""
    status_code: int
    r"""HTTP response status code for this operation"""
    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""
    response_update_channel_api_v1_notifications_channels_channel_id_patch: NotRequired[
        UpdateChannelAPIV1NotificationsChannelsChannelIDPatchResponseUpdateChannelAPIV1NotificationsChannelsChannelIDPatchTypedDict
    ]
    r"""Successful Response"""


class UpdateChannelAPIV1NotificationsChannelsChannelIDPatchResponse(BaseModel):
    content_type: str
    r"""HTTP response content type for this operation"""

    status_code: int
    r"""HTTP response status code for this operation"""

    raw_response: httpx.Response
    r"""Raw HTTP response; suitable for custom response parsing"""

    response_update_channel_api_v1_notifications_channels_channel_id_patch: Optional[
        UpdateChannelAPIV1NotificationsChannelsChannelIDPatchResponseUpdateChannelAPIV1NotificationsChannelsChannelIDPatch
    ] = None
    r"""Successful Response"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["Response Update Channel Api V1 Notifications Channels  Channel Id  Patch"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
