"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 98a0ae4bf6aa

from typing import Any, TYPE_CHECKING

from unstructured_client.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from . import errors, operations, shared

# package


_sub_packages = ["errors", "operations", "shared"]


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports={}, sub_packages=_sub_packages
    )


def __dir__():
    return lazy_dir(dynamic_imports={}, sub_packages=_sub_packages)
