"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 930e2548bef5

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from typing import Optional
from unstructured_client.models.errors import UnstructuredClientError
from unstructured_client.types import BaseModel


class ServerErrorData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class ServerError(UnstructuredClientError):
    data: ServerErrorData = field(hash=False)

    def __init__(
        self,
        data: ServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
